version: '3.8'
services:
  db:
    container_name: postgres
    image: postgres
    ports:
      - 5432:${POSTGRES_PORT}
    volumes:
      - data:/data/db
      - ./db:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
  api:
    container_name: api
    restart: always
    build: .
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - db
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
volumes:
  data: {}